In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('../data_out/20260227_205500.csv')
df = df.drop(columns=["position_fen"])
df.head()

,position_side_to_move,move_rank,move_san,move_eval_cp,move_eval_mate,move_eval_depth,source_lichess_user_total,source_lichess_user_share_percent,source_lichess_user_white_count,source_lichess_user_draw_count,...,source_chesscom_user_draw_percent,source_chesscom_user_black_percent,source_lichess_db_total,source_lichess_db_share_percent,source_lichess_db_white_count,source_lichess_db_draw_count,source_lichess_db_black_count,source_lichess_db_white_percent,source_lichess_db_draw_percent,source_lichess_db_black_percent
0,black,1,e4,18,NaN,70,1276.0,67.0,631.0,27.0,...,1.3,51.1,4376053752,58.6,2166238386,167911911,2041903455,49.5,3.8,46.7
1,black,2,d4,15,NaN,65,455.0,23.9,247.0,6.0,...,1.7,34.5,1873532496,25.1,945105336,76084669,852342491,50.4,4.1,45.5
2,black,3,c4,19,NaN,65,41.0,2.2,19.0,1.0,...,0.0,83.3,242581291,3.2,123147255,10107994,109326042,50.8,4.2,45.1
3,black,4,Nf3,10,NaN,60,34.0,1.8,24.0,1.0,...,0.0,42.9,265378110,3.6,135536587,11555780,118285743,51.1,4.4,44.6
4,black,5,b3,0,NaN,55,19.0,1.0,14.0,0.0,...,20.0,0.0,117479049,1.6,59247273,4347628,53884148,50.4,3.7,45.9

In [6]:
df.columns

Index(['position_side_to_move', 'move_rank', 'move_san', 'move_eval_cp',
       'move_eval_mate', 'move_eval_depth', 'source_lichess_user_total',
       'source_lichess_user_share_percent', 'source_lichess_user_white_count',
       'source_lichess_user_draw_count', 'source_lichess_user_black_count',
       'source_lichess_user_white_percent', 'source_lichess_user_draw_percent',
       'source_lichess_user_black_percent', 'source_chesscom_user_total',
       'source_chesscom_user_share_percent',
       'source_chesscom_user_white_count', 'source_chesscom_user_draw_count',
       'source_chesscom_user_black_count',
       'source_chesscom_user_white_percent',
       'source_chesscom_user_draw_percent',
       'source_chesscom_user_black_percent', 'source_lichess_db_total',
       'source_lichess_db_share_percent', 'source_lichess_db_white_count',
       'source_lichess_db_draw_count', 'source_lichess_db_black_count',
       'source_lichess_db_white_percent', 'source_lichess_db_draw_percent',
       'source_lichess_db_black_percent'],
      dtype='str')

In [ ]:
df["diff"] = (
    df["source_lichess_user_black_percent"] - df["source_lichess_db_black_percent"]
)
df["total"] = df["source_lichess_user_total"] + df["source_chesscom_user_total"]
df["perc"] = df["total"] / df["total"].sum() * 100
df["cum_perc"] = df["perc"].cumsum()
df["pot"] = df["diff"] * df["perc"]
df["pot_cum"] = df["pot"].where(df["pot"] < 0, 0).cumsum()

df[
    [
        "move_san",
        "move_eval_cp",
        "source_lichess_user_total",
        "source_lichess_user_black_percent",
        "source_lichess_db_black_percent",
        "diff",
        "total",
        "perc",
        "cum_perc",
        "pot",
        "pot_cum",
    ]
]

,move_san,move_eval_cp,source_lichess_user_total,source_lichess_user_black_percent,source_lichess_db_black_percent,diff,total,perc,cum_perc,pot,pot_cum
0,e4,18,1276.0,48.4,46.7,1.7,1501.0,68.134362,68.134362,115.828416,0.000000
1,d4,15,455.0,44.4,45.5,-1.1,513.0,23.286428,91.420790,-25.615070,-25.615070
2,c4,19,41.0,51.2,45.1,6.1,47.0,2.133454,93.554244,13.014072,-25.615070
3,Nf3,10,34.0,26.5,44.6,-18.1,41.0,1.861099,95.415343,-33.685883,-59.300953
4,b3,0,19.0,26.3,45.9,-19.6,24.0,1.089424,96.504766,-21.352701,-80.653654
5,e3,8,14.0,42.9,48.8,-5.9,22.0,0.998638,97.503404,-5.891966,-86.545620
6,g3,10,14.0,71.4,45.9,25.5,18.0,0.817068,98.320472,20.835225,-86.545620
7,f4,-23,14.0,64.3,46.6,17.7,15.0,0.680890,99.001362,12.051748,-86.545620
8,d3,-15,10.0,60.0,48.3,11.7,11.0,0.499319,99.500681,5.842034,-86.545620
9,b4,-7,10.0,20.0,44.8,-24.8,NaN,NaN,NaN,NaN,-86.545620
10,Nc3,-4,6.0,16.7,46.9,-30.2,7.0,0.317749,99.818429,-9.596005,-96.141625
11,g4,-96,6.0,50.0,48.0,2.0,NaN,NaN,NaN,NaN,-96.141625
12,a3,-6,2.0,50.0,48.3,1.7,NaN,NaN,NaN,NaN,-96.141625
13,c3,0,1.0,100.0,47.9,52.1,2.0,0.090785,99.909215,4.729914,-96.141625
14,h4,-36,1.0,0.0,52.8,-52.8,NaN,NaN,NaN,NaN,-96.141625
15,a4,-21,1.0,0.0,51.0,-51.0,NaN,NaN,NaN,NaN,-96.141625
16,h3,-3,1.0,0.0,51.8,-51.8,2.0,0.090785,100.000000,-4.702678,-100.844303
17,f3,-77,NaN,NaN,51.7,NaN,NaN,NaN,NaN,NaN,-100.844303
18,Nh3,-42,NaN,NaN,52.0,NaN,NaN,NaN,NaN,NaN,-100.844303
19,Na3,-52,NaN,NaN,52.9,NaN,NaN,NaN,NaN,NaN,-100.844303