In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data_out/20260227_215902.csv')
df = df.drop(columns=["position_fen"])
df.head()

,position_side_to_move,move_rank,move_san,move_eval_cp,move_eval_mate,move_eval_depth,source_lichess_user_total,source_lichess_user_share_percent,source_lichess_user_white_count,source_lichess_user_draw_count,...,source_chesscom_user_draw_percent,source_chesscom_user_black_percent,source_lichess_db_total,source_lichess_db_share_percent,source_lichess_db_white_count,source_lichess_db_draw_count,source_lichess_db_black_count,source_lichess_db_white_percent,source_lichess_db_draw_percent,source_lichess_db_black_percent
0,white,1,e5,18,NaN,70,894.0,52.1,502.0,17.0,...,1.4,52.1,1768754125,40.5,901609896,67128778,800015451,51.0,3.8,45.2
1,white,2,c5,25,NaN,56,237.0,13.8,113.0,6.0,...,8.1,37.8,767082863,17.6,367333486,30193392,369555985,47.9,3.9,48.2
2,white,3,d5,54,NaN,63,145.0,8.4,69.0,5.0,...,0.0,44.4,466969688,10.7,227452932,17896430,221620326,48.7,3.8,47.5
3,white,4,e6,22,NaN,60,142.0,8.3,79.0,3.0,...,7.0,34.9,445185883,10.2,213905477,17437306,213843100,48.0,3.9,48.0
4,white,5,c6,31,NaN,58,125.0,7.3,62.0,2.0,...,0.0,53.3,315940676,7.2,149710709,13034530,153195437,47.4,4.1,48.5

In [3]:
df.columns

Index(['position_side_to_move', 'move_rank', 'move_san', 'move_eval_cp',
       'move_eval_mate', 'move_eval_depth', 'source_lichess_user_total',
       'source_lichess_user_share_percent', 'source_lichess_user_white_count',
       'source_lichess_user_draw_count', 'source_lichess_user_black_count',
       'source_lichess_user_white_percent', 'source_lichess_user_draw_percent',
       'source_lichess_user_black_percent', 'source_chesscom_user_total',
       'source_chesscom_user_share_percent',
       'source_chesscom_user_white_count', 'source_chesscom_user_draw_count',
       'source_chesscom_user_black_count',
       'source_chesscom_user_white_percent',
       'source_chesscom_user_draw_percent',
       'source_chesscom_user_black_percent', 'source_lichess_db_total',
       'source_lichess_db_share_percent', 'source_lichess_db_white_count',
       'source_lichess_db_draw_count', 'source_lichess_db_black_count',
       'source_lichess_db_white_percent', 'source_lichess_db_draw_percent',
       'source_lichess_db_black_percent'],
      dtype='str')

In [7]:
df["diff"] = (
    df["source_lichess_user_white_percent"] - df["source_lichess_db_white_percent"]
)
df["total"] = df["source_lichess_user_total"] + df["source_chesscom_user_total"]
df["perc"] = df["total"] / df["total"].sum() * 100
df["cum_perc"] = df["perc"].cumsum()
df["pot"] = df["diff"] * df["perc"]
df["pot_cum"] = df["pot"].where(df["pot"] < 0, 0).cumsum()

df[
    [
        "move_san",
        "move_eval_cp",
        "source_lichess_user_total",
        "source_lichess_user_white_percent",
        "source_lichess_db_white_percent",
        "diff",
        "total",
        "perc",
        "cum_perc",
        "pot",
        "pot_cum",
    ]
]

,move_san,move_eval_cp,source_lichess_user_total,source_lichess_user_white_percent,source_lichess_db_white_percent,diff,total,perc,cum_perc,pot,pot_cum
0,e5,18,894.0,56.2,51.0,5.2,1038.0,51.616111,51.616111,268.403779,0.000000
1,c5,25,237.0,47.7,47.9,-0.2,274.0,13.625062,65.241174,-2.725012,-2.725012
2,d5,54,145.0,47.6,48.7,-1.1,172.0,8.552959,73.794132,-9.408255,-12.133267
3,e6,22,142.0,55.6,48.0,7.6,185.0,9.199403,82.993536,69.915465,-12.133267
4,c6,31,125.0,49.6,47.4,2.2,140.0,6.961711,89.955246,15.315763,-12.133267
5,d6,43,58.0,48.3,49.1,-0.8,67.0,3.331676,93.286922,-2.665341,-14.798608
6,g6,55,35.0,34.3,48.6,-14.3,40.0,1.989060,95.275982,-28.443560,-43.242168
7,b6,68,24.0,41.7,49.9,-8.2,33.0,1.640975,96.916957,-13.455992,-56.698160
8,Nc6,44,21.0,52.4,50.0,2.4,29.0,1.442069,98.359025,3.460965,-56.698160
9,Nf6,68,20.0,50.0,48.4,1.6,22.0,1.093983,99.453008,1.750373,-56.698160
10,a6,44,5.0,60.0,50.4,9.6,7.0,0.348086,99.801094,3.341621,-56.698160
11,f5,144,3.0,33.3,51.3,-18.0,4.0,0.198906,100.000000,-3.580308,-60.278468
12,g5,141,3.0,66.7,53.2,13.5,NaN,NaN,NaN,NaN,-60.278468
13,f6,112,2.0,0.0,54.7,-54.7,NaN,NaN,NaN,NaN,-60.278468
14,h5,97,2.0,50.0,53.6,-3.6,NaN,NaN,NaN,NaN,-60.278468
15,a5,76,1.0,0.0,56.0,-56.0,NaN,NaN,NaN,NaN,-60.278468
16,h6,63,NaN,NaN,52.5,NaN,NaN,NaN,NaN,NaN,-60.278468
17,b5,130,NaN,NaN,58.3,NaN,NaN,NaN,NaN,NaN,-60.278468
18,Nh6,94,NaN,NaN,54.5,NaN,NaN,NaN,NaN,NaN,-60.278468
19,Na6,90,NaN,NaN,61.0,NaN,NaN,NaN,NaN,NaN,-60.278468